### ISSUE TITLE
feature: calling plugins from each other

### ISSUE THREAD

**Issue by artoniemi** [veraison/veraison#168]
In our project, we need to verify nested attestation evidences. The outer-most evidence has type X (custom format), while the inner-most evidence has type Y (e.g. DICE certificate or TPM quote). There should be an easy way for the verification plugin for format X to call the plugin for format Y, so that the plugin for X doesn't need to be able to handle type Y.

**Comment by thomas-fossati** [comment]
This looks like a major architectural change, and one that I am not sure about because of the complexity introduced by an extra level of coupling.  I think we can achieve code reuse in different, simpler, ways.   Anyway, if you could come up with a concrete design proposal we can discuss it in the weekly.

**Comment by yogeshbdeshpande** [comment]
This issue is now tracked under:
https://github.com/veraison/services/issues/83
