### ISSUE TITLE
feature: define demostone for active provenance API

### ISSUE THREAD

**Issue by SimonFrost-Arm** [veraison/veraison#77]
Previous demostone achieved was for a standalone demo of verification pipeline working with PSA attestation tokens against a pre-canned set of endorsements/RVs.
Next demostone: standalone demo for verification of PSA tokens working against an endorsement store populated via a provisioning API. Extension of the Attestation Results generated by the verification pipeline to support the normalised set of Attestation results being proposed within RATS.

TBD: capture work items in order to estimate target timeframe

**Comment by yogeshbdeshpande** [comment]
@SimonFrost-Arm : As part of tidying up veraison issues, just wanted to check with you, is this still an issue.

To best of my understanding, we have Provisioning API and Verification API and a Demo story for End to End PSA.

Kindly update so that we can move it to correct repo, if still we need to do more work on this.
Else we can close this?

**Comment by yogeshbdeshpande** [comment]
The milestone was achieved with End to End Demo working for PSA!
